# Generated by Django 4.2.7 on 2023-11-26 21:38

import datetime
import django.core.validators
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Default",
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=5)
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="I shoud do it",
                        max_length=500,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=20)
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "due_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 26, 21, 38, 22, 28774),
                        validators=[tasks.models.validate_date],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
