# Generated by Django 4.2.7 on 2023-11-26 21:41

import datetime
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 26, 21, 41, 1, 961649, tzinfo=datetime.timezone.utc
                ),
                validators=[tasks.models.validate_date],
            ),
        ),
    ]
