# Generated by Django 4.2.7 on 2023-11-26 21:43

from django.db import migrations, models
import django.utils.timezone
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[tasks.models.validate_date],
            ),
        ),
    ]
